version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-aprovati
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: aprovati
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: