package com.aprovati.entity;

public enum Disciplina {

    ENGENHARIA_DE_SOFTWARE,
    METODOLOGIA_DE_DESENVOLVIMENTO_DE_SOFTWARE,
    DEVOPS_E_DEVSECOPS,
    ORIENTACAO_A_OBJETOS,
    GERENCIA_DE_PROJETOS_SERVICOS_E_GOVERNANCA_DE_TI,
    PROGRAMACAO,
    DESENVOLVIMENTO_WEB_E_MOBILE,
    DESENVOLVIMENTO_DE_SOFTWARE_SEGURO,
    INTELIGENCIA_ARTIFICIAL,
    BANCO_DE_DADOS,
    NOCOES_DE_INFRAESTRUTURA,
    ARQUITETURAS,
    SEGURANCA_DE_REDES,
    REDES,
    SEGURANCA_DA_INFORMACAO,
    OUTRO
}